/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Camera3d/scene.gltf 
Author: Low Poly Models (https://sketchfab.com/LowPolyModelsWorld)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/photography-studio-equipment-0a727c4d48d44c569bad774020897b3f
Title: Photography Studio Equipment
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.LowPolyModelsWorld} position={[-5.875, 0, -0.394]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.LowPolyModelsWorld} position={[-5.931, 0, 2.242]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.LowPolyModelsWorld} position={[-5.931, 0, 3.709]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.LowPolyModelsWorld} position={[-2.452, 0, 1.114]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.LowPolyModelsWorld} position={[-4.467, 0, 1.206]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.LowPolyModelsWorld} position={[-2.452, 0, 2.175]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.LowPolyModelsWorld} position={[-4.421, 0, 2.326]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.LowPolyModelsWorld} position={[-4.407, 0, -0.463]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.LowPolyModelsWorld} position={[-4.421, 0, 3.614]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.LowPolyModelsWorld} position={[-2.461, 0, -0.419]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.LowPolyModelsWorld} position={[-2.238, 0, -3.778]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.LowPolyModelsWorld} position={[-2.238, 0, -1.975]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.LowPolyModelsWorld} position={[-2.452, 0, 3.647]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.LowPolyModelsWorld} position={[-4.386, 0, -2.034]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.LowPolyModelsWorld} position={[-5.825, 0, -2.136]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.LowPolyModelsWorld} position={[-4.307, 0, -3.847]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.LowPolyModelsWorld} position={[0.571, 0, 1.388]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.LowPolyModelsWorld} position={[-5.768, 0, -3.757]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.LowPolyModelsWorld} position={[0, 0, 0.008]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.LowPolyModelsWorld} position={[-5.931, 0, 1.185]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
